spring.application.name=AplicacaoCarros
spring.datasource.url=jdbc:postgresql://localhost/aplicacao_carros
spring.datasource.username=postgres
spring.datasource.password=@AMS10052001ams
spring.datasource.driver-class-name=org.postgresql.Driver
hibernate.dialect=org.hibernate.dialect.HSQLDialect

spring.jpa.hibernate.ddl-auto=update
server.error.include-stacktrace=never
server.error.include-message=always
